### ISSUE TITLE
Consider using static class methods instead of prefixed functions

### ISSUE THREAD

**Issue by deltafactory** [nexusthemes/nxs-woobridge#1]
This gist contains a refactored main plugin file. It is untested code and may not actually run due to basic syntax errors.
https://gist.github.com/deltafactory/693e3de1dcf0efe2c19d

The purpose is to demo code that is organized within a class for readability and better understanding of interrelations of the function calls.

You are welcome to include it in your project as you see fit.

**Comment by barkgj** [comment]
Perhaps later, won't do it at this moment in time.
